default_context:
  project_name: 'osm'
  project_slug: 'osm'
  domain_main: 'https://cmn.nimh.nih.gov/dsst/osm'
  domain_staging: 'https://cmn.nimh.nih.gov/dsst/osm-staging'
  domain_base_api_url: 'http://https://cmn.nimh.nih.gov/dsst/osm/api/v1'
  domain_base_ws_url: 'ws://https://cmn.nimh.nih.gov/dsst/osm/api/v1'
  docker_swarm_stack_name_main: 'osm'
  docker_swarm_stack_name_staging: 'osm-staging'
  secret_key: 'd927ad2322072145572f05cf821189a6114cb9ae84aef77d9f2b225c832d5d13'
  first_superuser: 'leej3'
  first_superuser_password: '58de74852bd37f050e95c99dcbaf879232d0d44cf8cba03d42cbb5c7832f284c'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.https://cmn.nimh.nih.gov/dsst/osm", "https://https://cmn.nimh.nih.gov/dsst/osm-staging", "https://https://cmn.nimh.nih.gov/dsst/osm"]'
  smtp_tls: 'True'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@https://cmn.nimh.nih.gov/dsst/osm'
  smtp_emails_from_name: 'Symona Adaro'
  smtp_emails_to_email: 'info@https://cmn.nimh.nih.gov/dsst/osm'
  mongodb_uri: 'mongodb+srv://johnlee:0OQuTcjWK8U94fcW@cluster0.6xo8ws7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
  mongodb_database: 'app'
  traefik_constraint_tag: 'https://cmn.nimh.nih.gov/dsst/osm'
  traefik_constraint_tag_staging: 'https://cmn.nimh.nih.gov/dsst/osm-staging'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:58de74852bd37f050e95c99dcbaf879232d0d44cf8cba03d42cbb5c7832f284c'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/**/*.html, frontend/**/*.vue, frontend/.nuxt/*, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
