name: "Build and upload Docker image for releases"

on:
  push:
    tags: ["*"]
  workflow_dispatch:

jobs:
  build_and_push_docker_image:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to Docker Hub 🐳"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Add Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            timdanaos/app
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=sha

      - name: "Publish Docker image"
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            ${{ steps.meta.outputs.tags }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/')
